_wandb:
    value:
        cli_version: 0.22.3
        e:
            gltv9bk48ir7eaw08eqshb9ay0sk3i07:
                codePath: .vscode\code\train
                codePathLocal: .vscode\code\train
                cpu_count: 8
                cpu_count_logical: 12
                disk:
                    /:
                        total: "506333229056"
                        used: "136479621120"
                email: be.yael.10@gmail.com
                executable: C:\Users\beyae\Documents\coco-keypoint-estimation\.venv\Scripts\python.exe
                git:
                    commit: f89faae29b82eda23d19869ede2e1c2d25897f78
                    remote: https://github.com/xYaelx/coco-keypoint-estimation.git
                host: Johnny
                memory:
                    total: "16890322944"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\beyae\Documents\coco-keypoint-estimation\.vscode\code\train
                python: CPython 3.11.14
                root: C:\Users\beyae\Documents\coco-keypoint-estimation
                startedAt: "2025-11-05T11:35:08.161759Z"
                writerId: gltv9bk48ir7eaw08eqshb9ay0sk3i07
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 5
lr:
    value: 0.001
